CREATE TABLE `campaign_analytics` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`campaign_id` integer NOT NULL,
	`date` integer NOT NULL,
	`impressions` integer DEFAULT 0,
	`clicks` integer DEFAULT 0,
	`conversions` integer DEFAULT 0,
	`revenue` real DEFAULT 0,
	`cost` real DEFAULT 0,
	`bounce_rate` real,
	`open_rate` real,
	`click_rate` real,
	`conversion_rate` real,
	`unsubscribe_rate` real,
	`created_at` integer,
	FOREIGN KEY (`campaign_id`) REFERENCES `campaigns`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `campaigns` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tenant_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`type` text NOT NULL,
	`status` text DEFAULT 'draft',
	`target_segment` integer,
	`target_criteria` text,
	`start_date` integer,
	`end_date` integer,
	`budget` real,
	`currency` text DEFAULT 'ZAR',
	`expected_reach` integer,
	`content` text,
	`automation_rules` text,
	`created_by` integer,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`target_segment`) REFERENCES `customer_segments`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `communications` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tenant_id` text NOT NULL,
	`customer_id` integer,
	`lead_id` integer,
	`campaign_id` integer,
	`type` text NOT NULL,
	`direction` text,
	`subject` text,
	`content` text,
	`status` text,
	`sent_at` integer,
	`delivered_at` integer,
	`read_at` integer,
	`replied_at` integer,
	`performed_by` integer,
	`metadata` text,
	`created_at` integer,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lead_id`) REFERENCES `leads`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`campaign_id`) REFERENCES `campaigns`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`performed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `customer_feedback` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tenant_id` text NOT NULL,
	`customer_id` integer,
	`lead_id` integer,
	`type` text NOT NULL,
	`rating` integer,
	`subject` text,
	`message` text NOT NULL,
	`category` text,
	`status` text DEFAULT 'new',
	`assigned_to` integer,
	`response` text,
	`responded_at` integer,
	`is_public` integer DEFAULT false,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lead_id`) REFERENCES `leads`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`assigned_to`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `customer_segments` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tenant_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`criteria` text,
	`customer_count` integer DEFAULT 0,
	`is_active` integer DEFAULT true,
	`created_at` integer,
	`updated_at` integer
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer,
	`tenant_id` text NOT NULL,
	`customer_number` text NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`date_of_birth` integer,
	`gender` text,
	`address` text,
	`city` text,
	`province` text,
	`postal_code` text,
	`country` text DEFAULT 'South Africa',
	`status` text DEFAULT 'active',
	`customer_type` text DEFAULT 'individual',
	`segment_id` integer,
	`company_name` text,
	`company_size` text,
	`industry` text,
	`preferred_language` text DEFAULT 'en',
	`communication_preferences` text,
	`total_spent` real DEFAULT 0,
	`total_orders` integer DEFAULT 0,
	`last_order_date` integer,
	`lifetime_value` real DEFAULT 0,
	`churn_risk` text DEFAULT 'low',
	`source` text,
	`tags` text,
	`custom_fields` text,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`segment_id`) REFERENCES `customer_segments`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `customers_customer_number_unique` ON `customers` (`customer_number`);--> statement-breakpoint
CREATE TABLE `leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tenant_id` text NOT NULL,
	`lead_number` text NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`company` text,
	`source` text,
	`source_details` text,
	`status` text DEFAULT 'new',
	`priority` text DEFAULT 'medium',
	`estimated_value` real,
	`probability` real,
	`score` integer DEFAULT 0,
	`assigned_to` integer,
	`qualification_notes` text,
	`next_follow_up` integer,
	`converted_customer_id` integer,
	`converted_at` integer,
	`tags` text,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`assigned_to`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`converted_customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `leads_lead_number_unique` ON `leads` (`lead_number`);--> statement-breakpoint
CREATE TABLE `loyalty_points` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`customer_id` integer NOT NULL,
	`program_id` integer NOT NULL,
	`points` integer NOT NULL,
	`transaction_type` text NOT NULL,
	`transaction_id` text,
	`description` text,
	`expiry_date` integer,
	`balance_after` integer,
	`performed_by` integer,
	`created_at` integer,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`program_id`) REFERENCES `loyalty_programs`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`performed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `loyalty_programs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tenant_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`type` text DEFAULT 'points',
	`is_active` integer DEFAULT true,
	`point_value` real DEFAULT 1,
	`currency` text DEFAULT 'ZAR',
	`tiers` text,
	`rules` text,
	`expiry_days` integer,
	`created_at` integer,
	`updated_at` integer
);
